# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-18 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20180708_1306'),
        ('common', '0008_auto_20180708_1702'),
    ]

    operations = [
    ]
