# Generated by Django 2.0.6 on 2018-07-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='commandssequence',
            name='group',
            field=models.ManyToManyField(to='common.ServerGroup', verbose_name='Server group you want to execute'),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Log', verbose_name='Log'),
        ),
        migrations.AlterUniqueTogether(
            name='serverinfor',
            unique_together={('ip', 'credential')},
        ),
    ]
