# Generated by Django 2.0.6 on 2018-07-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text='Set the role for the user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.Role'),
        ),
    ]
