# Generated by Django 2.0.6 on 2018-07-02 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180701_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAWSKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesskey_id', models.CharField(blank=True, max_length=20)),
                ('accesskey_secret', models.CharField(blank=True, max_length=40)),
                ('account', models.CharField(blank=True, help_text="Account For Key, e.g. 'prod', 'non-prod'", max_length=32)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userawskeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
