# Generated by Django 2.0.6 on 2018-07-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayslog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayslog',
            name='happenings',
            field=models.TextField(default='<h1>Things that happened today</h1>\n<ol>\n  <li>Clock ticked over midnight.</li>\n</ol>'),
        ),
    ]
