# Generated by Django 2.0.6 on 2018-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scribble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=64)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scribble',
            unique_together={('slug', 'url')},
        ),
    ]
